spring:
  datasource:
    url: jdbc:postgresql://localhost/workflow
    username: workflow
    password: workflow
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
---
spring:
  config:
    activate:
      on-profile: iseletkov

  datasource:
    url: jdbc:postgresql://192.168.1.102:50000/techjava
    username: workflow
    password: workflow
